[versions]

# libraries

telegrambots          = "9.0.0"
fastutil              = "8.5.16"
google-guava          = "33.4.8-jre"
google-jsr305         = "3.0.2"
jetbrains-annotations = "26.0.2"
junit-jupiter         = "5.13.4"
junit-platform        = "1.13.4"
yaml-snakeyaml        = "2.4"

# plugins

shadow                       = "8.3.3"
spring-boot                  = "3.5.4"
spring-dependency-management = "1.1.7"
suggestbot-plugins           = "1.0.0"

[libraries]

# libraries

fastutil                        = { group = "it.unimi.dsi",             name = "fastutil",                                    version.ref = "fastutil" }
google-guava                    = { group = "com.google.guava",         name = "guava",                                       version.ref = "google-guava" }
google-jsr305                   = { group = "com.google.code.findbugs", name = "jsr305",                                      version.ref = "google-jsr305" }
jetbrains-annotations           = { group = "org.jetbrains",            name = "annotations",                                 version.ref = "jetbrains-annotations" }
junit-jupiter                   = { group = "org.junit.jupiter",        name = "junit-jupiter",                               version.ref = "junit-jupiter" }
junit-platform-launcher         = { group = "org.junit.platform",       name = "junit-platform-launcher" }
micrometer-prometheus           = { group = "io.micrometer",            name = "micrometer-registry-prometheus" }
postgresql                      = { group = "org.postgresql",           name = "postgresql" }
spring-actuator                 = { group = "org.springframework.boot", name = "spring-boot-starter-actuator" }
spring-amqp                     = { group = "org.springframework.boot", name = "spring-boot-starter-amqp" }
spring-configuration-processor  = { group = "org.springframework.boot", name = "spring-boot-configuration-processor" }
spring-data-jpa                 = { group = "org.springframework.boot", name = "spring-boot-starter-data-jpa" }
spring-data-redis               = { group = "org.springframework.boot", name = "spring-boot-starter-data-redis" }
spring-devtools                 = { group = "org.springframework.boot", name = "spring-boot-devtools" }
spring-rabbitmq-test            = { group = "org.springframework.amqp", name = "spring-rabbit-test" }
spring-test                     = { group = "org.springframework.boot", name = "spring-boot-starter-test" }
spring-web                      = { group = "org.springframework.boot", name = "spring-boot-starter-web" }
telegram-client                 = { group = "org.telegram",             name = "telegrambots-client",                         version.ref = "telegrambots" }
telegram-spring-longpolling     = { group = "org.telegram",             name = "telegrambots-springboot-longpolling-starter", version.ref = "telegrambots" }
yaml-snakeyaml                  = { group = "org.yaml",                 name = "snakeyaml",                                   version.ref = "yaml-snakeyaml" }

# plugins

plugin-shadow                       = { group = "com.gradleup.shadow",             name = "shadow-gradle-plugin",                          version.ref = "shadow" }
plugin-spring-boot                  = { group = "org.springframework.boot",        name = "spring-boot-gradle-plugin",                     version.ref = "spring-boot" }
plugin-spring-dependency-management = { group = "io.spring.dependency-management", name = "io.spring.dependency-management.gradle.plugin", version.ref = "spring-dependency-management" }

[plugins]

# internal plugins

suggestbot-base    = { id = "suggestbot.base" }
suggestbot-library = { id = "suggestbot.library" }
suggestbot-service = { id = "suggestbot.service" }

# external plugins

shadow                       = { id = "com.gradleup.shadow",             version.ref = "shadow" }
spring-boot                  = { id = "org.springframework.boot",        version.ref = "spring-boot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "spring-dependency-management" }
