blank_issues_enabled: false
contact_links:
  - name: 🌐 Website
    url: https://nykon.me/
    about: Check out my website
  - name: 💬 Telegram
    url: https://nykon.me/telegram
    about: Join my Telegram channel
