# This file overrides the "docker-compose.dev.yml" file.
# It is used to build the application artifacts in a separate builder service.

# Defaults for services that depend on the builder service
x-depends-on-builder: &depends-on-builder
  depends_on:
    builder:
      condition: service_completed_successfully

services:
  # The builder service is responsible for building the application artifacts
  # and placing them in a shared volume "build-artifacts:/output".
  builder:
    container_name: service_builder
    env_file:
      - ".env"
      - ".env.build"
    build:
      context: ..
      dockerfile: docker/builder/dev.Dockerfile
    volumes:
      - build-artifacts:/output
      - gradle-cache:/home/gradle/.gradle

  # Expected that the "bot" service already exists in the overridden file.
  # It will wait for the "builder" service to complete the build successfully.
  bot:
    <<: *depends-on-builder

  # Expected that the "worker" service already exists in the overridden file.
  # It will wait for the "builder" service to complete the build successfully.
  worker:
    <<: *depends-on-builder
