global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:${PROMETHEUS_PORT}']

  - job_name: 'bot'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['bot:${BOT_PORT}']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: "bot"

  - job_name: 'worker'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['worker:${WORKER_PORT}']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: "worker"
