spring:
  application:
    name: SuggestionsBot

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

  rabbitmq:
    username: ${RABBITMQ_DEFAULT_USER}
    password: ${RABBITMQ_DEFAULT_PASS}
    virtual-host: ${RABBITMQ_DEFAULT_VHOST}
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}

management:
  endpoints:
    access:
      default: none
    web:
      exposure:
        include: health
        exclude: env, beans, metrics, shutdown, loggers, heapdump

  endpoint:
    health:
      access: read_only
      show-details: always

  server:
    port: ${BOT_PORT}

logging:
  level:
    root: info
