services:
  builder:
    build:
      context: ..
      dockerfile: docker/builder/dev.Dockerfile
    volumes:
      - build-artifacts:/output

  bot:
    build:
      context: ..
      dockerfile: docker/service-bot/dev.Dockerfile
    depends_on:
      builder:
        condition: service_completed_successfully
    volumes:
      - build-artifacts:/app
    ports:
      - "8080:8080"

  worker:
    build:
      context: ..
      dockerfile: docker/service-worker/dev.Dockerfile
    depends_on:
      builder:
        condition: service_completed_successfully
    volumes:
      - build-artifacts:/app
    ports:
      - "5432:5432"

volumes:
  build-artifacts:
