spring:
  application:
    name: SuggestionsWorker

  datasource:
    url: jdbc:postgresql://postgres:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: redis
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

management:
  endpoints:
    access:
      default: none
    web:
      exposure:
        include: health
        exclude: env, beans, metrics, shutdown, loggers, heapdump

  endpoint:
    health:
      access: read_only
      show-details: always

  server:
    port: ${WORKER_PORT}

logging:
  level:
    root: info
