spring:
  application:
    name: SuggestionsWorker
  sql:
    init:
      mode: never
      continue-on-error: true
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
  rabbitmq:
    username: ${RABBITMQ_DEFAULT_USER}
    password: ${RABBITMQ_DEFAULT_PASS}
    virtual-host: ${RABBITMQ_DEFAULT_VHOST}
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
        exclude: env, beans, shutdown, loggers, heapdump
  endpoint:
    health:
      access: read_only
      show-details: always
  info:
    env:
      enabled: true
  metrics:
    enable:
      all: true
  server:
    port: ${WORKER_PORT}

logging:
  level:
    root: info
